# Generated by Django 5.2.10 on 2026-01-19 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.CharField(max_length=80, unique=True)),
                (
                    "instrument",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("run_group", models.CharField(blank=True, default="", max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SpecimenMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_id", models.CharField(max_length=80)),
                ("specimen_name", models.CharField(max_length=120)),
                (
                    "specimen_type",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("TUMOR", "Tumor"),
                            ("CONTROL", "Control"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source_filename",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("ingested_at", models.DateTimeField(blank=True, null=True)),
                ("mapped_reads", models.IntegerField(blank=True, null=True)),
                ("contamination", models.FloatField(blank=True, null=True)),
                ("mean_coverage", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specimens",
                        to="reviews.batchrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QcDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("PASS", "PASS"),
                            ("FAIL", "FAIL"),
                            ("PENDING", "PENDING"),
                            ("NEEDS_REPEAT", "NEEDS_REPEAT"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True, default="")),
                ("decided_at", models.DateTimeField()),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="qc_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "specimen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="reviews.specimenmetric",
                    ),
                ),
            ],
            options={
                "ordering": ["-decided_at"],
            },
        ),
        migrations.AddIndex(
            model_name="specimenmetric",
            index=models.Index(
                fields=["case_id"], name="reviews_spe_case_id_bce3b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="specimenmetric",
            index=models.Index(
                fields=["specimen_type"], name="reviews_spe_specime_60812b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qcdecision",
            index=models.Index(
                fields=["decision", "decided_at"], name="reviews_qcd_decisio_f075e8_idx"
            ),
        ),
    ]
